# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do
  before_all do
    ENV["FASTLANE_DONT_STORE_PASSWORD"] = "1"
    ENV["FASTLANE_USER"] = "Mohammad.Jeeshan@quokkalabs.com"
    ENV["FASTLANE_PASSWORD"] = "Mustafa@92"
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "ciyg-pron-ibwt-xuci"
  end
  desc "Description of what the lane does"
  lane :betaLane do
    build_app(scheme: "TestingCi")
    upload_to_testflight           
  end
end

